apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendation-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kemrictomta/devops-full-project.git
    targetRevision: main
    path: ultimate-devops-project-demo/k8s/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
