apiVersion: apps/v1
kind: Deployment

metadata:
  name: recommendation-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: recommendation-service

  template:
    metadata:
      labels:
        app: recommendation-service

    spec:
      containers:
        - name: recommendation-service

          image: europe-west3-docker.pkg.dev/project-43bc1e62-02df-4e0f-917/microservices/recommendation:v1.0

          env:
            - name: OTEL_SERVICE_NAME
              value: "recommendation"
            - name: PRODUCT_CATALOG_ADDR
              value: "product-catalog:3550"
            - name: RECOMMENDATION_PORT
              value: "9001"

          ports:
            - containerPort: 9001
