name: Build and Deploy Recommendation

on:
  push:
    branches:
      - main
    paths:
      - "ultimate-devops-project-demo/src/recommendation/**"
      - "ultimate-devops-project-demo/k8s/**"
      - ".github/workflows/recommendation-deploy.yaml"

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-43bc1e62-02df-4e0f-917
  REGION: europe-west3
  CLUSTER_NAME: my-platform-gke
  REGISTRY: europe-west3-docker.pkg.dev
  IMAGE_NAME: project-43bc1e62-02df-4e0f-917/microservices/recommendation

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/75035229141/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@project-43bc1e62-02df-4e0f-917.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Configure Docker auth
        run: gcloud auth configure-docker $REGISTRY --quiet

      - name: Build image
        run: |
          docker build -f ultimate-devops-project-demo/src/recommendation/Dockerfile \
            -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            -t $REGISTRY/$IMAGE_NAME:latest \
            ultimate-devops-project-demo

      - name: Push image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME \
            --region $REGION \
            --project $PROJECT_ID

      - name: Deploy to staging
        run: |
          kubectl set image deployment/recommendation-service \
            recommendation-service=$REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            -n staging
          kubectl rollout status deployment/recommendation-service -n staging

      - name: Deploy to production
        run: |
          kubectl set image deployment/recommendation-service \
            recommendation-service=$REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            -n production
          kubectl rollout status deployment/recommendation-service -n production --timeout=5m
